# Generated by Django 4.2.7 on 2023-11-16 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('callableuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active', models.BooleanField(default=True)),
                ('salt', models.BinaryField(max_length=255, null=True)),
                ('special_key', models.BinaryField(max_length=255, unique=True)),
                ('is_auto_password', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user_portal.callableuser',),
        ),
    ]
