# Generated by Django 4.2.7 on 2023-11-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='callableuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='callableuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callableuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
