# Generated by Django 4.2.7 on 2023-11-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0003_remove_saltedpasswordmodel_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='salt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
