# Generated by Django 4.2.7 on 2023-11-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0004_teacher_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callableuser',
            name='password',
        ),
    ]
