# Generated by Django 5.0.1 on 2024-01-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0007_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hour',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
